# Generated by Django 5.0.1 on 2024-02-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id_ano', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('periodo', models.IntegerField()),
            ],
            options={
                'db_table': 'ano',
            },
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('idt_consumidoras', models.AutoField(primary_key=True, serialize=False)),
                ('id_consumidoras', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'consumidor',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('sig_agente', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='DecFec',
            fields=[
                ('id_dec_fec', models.AutoField(primary_key=True, serialize=False)),
                ('sig_indicador', models.CharField(max_length=255)),
                ('vlr_indice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.ano')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.empresa')),
            ],
            options={
                'db_table': 'dec_fec',
            },
        ),
        migrations.CreateModel(
            name='Correlacao',
            fields=[
                ('id_correlacao', models.AutoField(primary_key=True, serialize=False)),
                ('kendall', models.DecimalField(decimal_places=10, max_digits=11)),
                ('spearman', models.DecimalField(decimal_places=10, max_digits=11)),
                ('id_dec_fec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.decfec')),
            ],
            options={
                'db_table': 'correlacao',
            },
        ),
        migrations.CreateModel(
            name='DadosAcoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Open', models.DecimalField(decimal_places=15, max_digits=18)),
                ('High', models.DecimalField(decimal_places=15, max_digits=18)),
                ('Low', models.DecimalField(decimal_places=15, max_digits=18)),
                ('Close', models.DecimalField(decimal_places=15, max_digits=18)),
                ('Adj_Close', models.DecimalField(decimal_places=15, max_digits=18)),
                ('Volume', models.IntegerField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.empresa')),
            ],
            options={
                'db_table': 'dados_acoes',
            },
        ),
        migrations.CreateModel(
            name='AnoConsumidor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.ano')),
                ('id_consumidoras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.consumidor')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.empresa')),
            ],
            options={
                'db_table': 'ano_consumidor',
            },
        ),
        migrations.CreateModel(
            name='DecFecConsumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_consumidoras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.consumidor')),
                ('id_dec_fec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.decfec')),
            ],
            options={
                'db_table': 'dec_fec_consumidor',
                'unique_together': {('id_consumidoras', 'id_dec_fec')},
            },
        ),
        migrations.CreateModel(
            name='DadosAcoesInclinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclinacao', models.DecimalField(decimal_places=17, max_digits=20)),
                ('id_ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.ano')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.empresa')),
            ],
            options={
                'db_table': 'dados_acoes_inclinacao',
                'unique_together': {('id_empresa', 'id_ano')},
            },
        ),
    ]
